# Generated by Django 3.0.3 on 2020-03-04 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypage',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='countrypage',
            name='firefighter',
        ),
        migrations.RemoveField(
            model_name='countrypage',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='countrypage',
            name='police',
        ),
    ]
