# Generated by Django 3.0.3 on 2020-03-04 07:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('country', '0002_auto_20200304_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypage',
            name='region',
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name_plural': 'region',
            },
        ),
        migrations.AddField(
            model_name='countrypage',
            name='region',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='country.Region'),
        ),
    ]
