# Generated by Django 3.0.3 on 2020-03-04 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_auto_20200304_1436'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskcategory',
            options={'verbose_name_plural': 'Country'},
        ),
        migrations.RemoveField(
            model_name='countrypage',
            name='region',
        ),
        migrations.AddField(
            model_name='countrypage',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.Region'),
        ),
    ]
