# Generated by Django 3.0.3 on 2020-03-04 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0005_auto_20200304_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrypage',
            name='country',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
