# Generated by Django 3.0.3 on 2020-03-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20200304_1449'),
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='riskcategory',
            options={'verbose_name_plural': 'City Risk'},
        ),
        migrations.RemoveField(
            model_name='citypage',
            name='country',
        ),
        migrations.AddField(
            model_name='citypage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.CountryPage'),
        ),
    ]
