# Generated by Django 3.0.3 on 2020-02-21 07:15

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('advisory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvisoryPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField(verbose_name='Post date')),
                ('title_id', models.CharField(max_length=250)),
                ('body_en', wagtail.core.fields.RichTextField(blank=True)),
                ('body_id', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
