# Generated by Django 3.0.3 on 2020-03-04 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0004_auto_20200304_1449'),
        ('advisory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advisorypage',
            name='categories',
        ),
        migrations.AddField(
            model_name='advisorypage',
            name='categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advisory.AdvisoryCategory'),
        ),
        migrations.RemoveField(
            model_name='advisorypage',
            name='country',
        ),
        migrations.AddField(
            model_name='advisorypage',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='country.CountryPage'),
        ),
    ]
