# Generated by Django 3.0.3 on 2020-02-21 07:43

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('advisory', '0005_advisorycategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorypage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='advisory.AdvisoryCategory'),
        ),
    ]
