# Generated by Django 3.0.3 on 2020-02-21 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('advisory', '0006_advisorypage_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='advisorypage',
            name='feed_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
