# Generated by Django 3.0.3 on 2020-02-21 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200221_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='title_id',
            field=models.CharField(default='Indonesia Version', max_length=250),
            preserve_default=False,
        ),
    ]
