# Generated by Django 3.0.3 on 2020-02-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200220_1637'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body_en_us',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body_ind',
        ),
    ]
