# Generated by Django 3.0.3 on 2020-03-04 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20200304_1458'),
        ('sites', '0002_auto_20200304_1420'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitecategory',
            options={'verbose_name_plural': 'Business Unit'},
        ),
        migrations.RemoveField(
            model_name='sitepage',
            name='city',
        ),
        migrations.AddField(
            model_name='sitepage',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='city.CityPage'),
        ),
    ]
